##' Plot Commodity Tree
##' 
##' This function is useful for visualizing the relationships between different
##' commodities as defined within the shareData dataset (see getShareData).
##' 
##' @param shareData The data.table containing the share information, typically
##' as generated by getShareData.
##' @param parentName The column name of shareData which contains the item code
##' of the parent.
##' @param childName The column name of shareData which contains the item code
##' of the child.
##' @param ... Additional parameters to be passed to the plot.igraph function.
##' 
##' @return No data is returned, but a plot of the commodity tree is drawn
##' using the igraph package.
##' 
##' @export
##' 

plotCommodityTree = function(shareData, parentName = "measuredItemParentFS",
                             childName = "measuredItemChildFS", ...){
    
    ## Data Quality Checks
    stopifnot(is(shareData, "data.table"))
    
    edges = shareData[, .N,by = c(parentName, childName)]
    edges[, N := NULL]
    commodityTree = igraph::graph.data.frame(edges)
    
    suppliedArgs = list(...)
    if(!"vertex.size" %in% names(suppliedArgs))
        suppliedArgs[["vertex.size"]] = 5
    if(!"edge.arrow.size" %in% names(suppliedArgs))
        suppliedArgs[["edge.arrow.size"]] = .1
    suppliedArgs[["x"]] = commodityTree
    do.call("plot", suppliedArgs)
}