##' US Sample dataset
##' 
##' An example dataset of what can be created from calling the function
##' getAupusDataset.
##' 
##' @docType data
##' @keywords aupus, dataset
##' @name US
##' @usage data(US)
##' @format A list object containing 8 individual datasets.  Each dataset is
##' generated by the corresponding get* function in the faoswsAupus package.
##' Most elements are data.tables, but some (such as the ratio and
##' balanceElement datasets) are lists of data.tables.  See the documentation
##' for the corresponding get* functions for more details.
##'
NULL